name: CI - Create tag

on:
  push:
    branches:
      - 'main'

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Bump version in package.json
        id: bump_version
        run: |
          yarn version --patch --no-git-tag-version
          echo "::set-output name=new_version::$(node -p -e "require('./package.json').version")"

      - name: Commit and push changes to package.json
        run: |
          git commit -am "Bump version to v${{ steps.bump_version.outputs.new_version }}"
          git push origin HEAD:main

      - name: Create and push tag
        id: create_tag
        run: |
          git tag v${{ steps.bump_version.outputs.new_version }}
          git push origin v${{ steps.bump_version.outputs.new_version }}
